version: '3'

services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8001"
    env_file:
      - .env
    command: --model $CHATBOT_MODEL --gpu-memory-utilization 0.80 --max-model-len 16348 --port 8001
    ipc: host

  app:
    image: scb:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    command: python start_bot.py
    depends_on:
      - vllm

networks:
  default:
    internal: true

